apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-auth2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: edu-auth2
  template:
    metadata:
      labels:
        app: edu-auth2
    spec:
      containers:
      - name: edu-auth2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP