{{- if and .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "demo-web.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.group }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.ssl }}
spec:
  rules:
    - host: {{ .Values.ingress.rules.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "demo-web.fullname" . }}
                port:
                  number: {{ .Values.ingress.rules.port }}
  tls:
    - hosts:
      - {{ .Values.ingress.rules.host }}
{{- end }}