replicaCount: 1

image:
  repository: 820883240614.dkr.ecr.ap-southeast-1.amazonaws.com/edu_auth
  pullPolicy: Always
  tag: "v1.0.6"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 31004

